### ISSUE TITLE
Go Live Checklist

### ISSUE THREAD

**Issue by JakeGWater** [JakeGWater/vpifg.com#38]
- [x] [guides](https://vpifg.com/guides/) needs content
- [x] [Workflows](https://vpifg.com/workflows/) links to nonexistent live guide
- [ ] [Burn](https://vpifg.com/workflows/BURN/)
  - [ ] fix slide size
  - [ ] add some exposition to the guide order
  - [x] indicate which guides are complete, and which are planned with an icon
- [x] Check all guides. Either DONE, or PLANNED or HELP
- [x] [Help](https://vpifg.com/help/) Section
- [ ] PROOF READ
- [x] Copy same banner from Patreon to /about
- [ ] Framework
  - [ ] [4k](https://vpifg.com/theory/4k/)
  - [ ] [ACES](https://vpifg.com/theory/aces/)
  - [ ] [RAW](https://vpifg.com/theory/raw/)
  - [ ] [Timecode](https://vpifg.com/theory/timecode/)
- [x] Add metadata to pages
- [x] Add [sponsorship](https://vpifg.com/#sponsor) info
